src/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import never_cache
from django.views.static import serve

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('product/', include('product.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, view=never_cache(serve))

src/product/urls.py
from django.urls import path
from django.views.generic import TemplateView

from product.views.product import CreateProductView,ProductList, UpdateProductView, uploadProductImage
from product.views.variant import VariantView, VariantCreateView, VariantEditView

from product.views.api.views import getProduct,createNewProduct,updateProduct
app_name = "product"

urlpatterns = [
    # Variants URLs
    path('variants/', VariantView.as_view(), name='variants'),
    path('variant/create', VariantCreateView.as_view(), name='create.variant'),
    path('variant/<int:id>/edit', VariantEditView.as_view(), name='update.variant'),
    # api call  
    path('api/get/<int:pk>/',getProduct,name='api.get.product'),
    path('api/create/', createNewProduct, name='api.create.product'),
    path('api/update/<int:pk>/', updateProduct, name='api.update.product'),
    # Products URLs
    path('uploadimages/', uploadProductImage, name='image.upload.product'),
    path('create/', CreateProductView.as_view(), name='create.product'),
    path('update/view/<int:pk>/', UpdateProductView.as_view(), name='update.product'),
    path('list/', ProductList.as_view(), name='list.product'),
]

src/product/models.py
from django.db import models

# Create your models here.
class Variant(models.Model):
    title = models.CharField(max_length=40)
    description = models.TextField()
    active = models.BooleanField(default=True)
    def __str__(self):
        return f'{self.id} . {self.title}'


class Product(models.Model):
    title = models.CharField(max_length=255)
    sku = models.SlugField(max_length=255)
    description = models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    file_path = models.URLField()


class ProductVariant(models.Model):
    variant_title = models.CharField(max_length=255)
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        try:
            return self.variant_title
        except:
            return '[none]'


class ProductVariantPrice(models.Model):
    product_variant_one = models.ForeignKey(ProductVariant, on_delete=models.CASCADE,
                                            related_name='product_variant_one',blank=True,null=True)
    product_variant_two = models.ForeignKey(ProductVariant, on_delete=models.CASCADE,
                                            related_name='product_variant_two',blank=True,null=True)
    product_variant_three = models.ForeignKey(ProductVariant, on_delete=models.CASCADE,
                                              related_name='product_variant_three',blank=True,null=True)
    price = models.FloatField()
    stock = models.FloatField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self) :
        val=[]

        try:
            val.append(self.product_variant_one.variant_title)
        except :
            pass 

        try:
            val.append(self.product_variant_two.variant_title)
        except :
            pass 

        try:
            val.append(self.product_variant_three.variant_title)
        except :
            pass 

        

        # print("val ",)

        return "/".join(val)

src/product/forms.py
from django.forms import forms, ModelForm, CharField, TextInput, Textarea, BooleanField, CheckboxInput

from product.models import Variant


class VariantForm(ModelForm):
    class Meta:
        model = Variant
        fields = '__all__'
        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control'}),
            'active': CheckboxInput(attrs={'class': 'form-check-input', 'id': 'active'})
        }

src/product/views/product.py
import datetime
from django.core.files.storage import FileSystemStorage

from django.http.response import JsonResponse
from django.views import generic


from product.models import ProductImage, ProductVariant, Variant,Product
from django.shortcuts import get_object_or_404
from django.db.models import Q


class CreateProductView(generic.TemplateView):
    template_name = 'products/create.html'

    def get_context_data(self, **kwargs):
        context = super(CreateProductView, self).get_context_data(**kwargs)
        variants = Variant.objects.filter(active=True).values('id', 'title')
        context['product'] = True
        context['variants'] = list(variants.all())
        return context

class UpdateProductView(generic.TemplateView):
    template_name = 'products/update.html'

    def get_context_data(self, **kwargs):
        context = super(UpdateProductView, self).get_context_data(**kwargs)
        variants = Variant.objects.filter(active=True).values('id', 'title')

        context['product'] = True
        context['variants'] = list(variants.all())

        # context['object']= Product.objects.get(kwargs.get('pk'))
        get_object_or_404(Product,pk=kwargs.get('pk'))
        context['pk']=kwargs.get('pk')


        return context



def uploadProductImage(request):
    # print(request.POST)
    if request.method=='POST':
        pk=request.POST.get('pk')
        product=get_object_or_404(Product,pk=pk)
        for key in request.FILES:
            
            fs = FileSystemStorage()
            filename = fs.save('product_images/'+request.FILES[key].name, request.FILES[key])
            uploaded_file_url = fs.url(filename)

            ProductImage.objects.create(
                product=product,
                file_path=uploaded_file_url
            )
        return JsonResponse(data={"details":"image been uploaded"}) 
    return JsonResponse(data={'detail':"opps"},status_code=404)

class ProductList(generic.ListView):
    template_name='products/list.html'
    model = Product 
    paginate_by = 2
    def get_queryset(self) :

        title=self.request.GET.get('title',None)
        price_from=self.request.GET.get('price_from',None)
        price_to=self.request.GET.get('price_to',None)
        date=self.request.GET.get('date',None)
        variant=self.request.GET.get('variant',None)

        
        # print('here',)
            



        qs= Product.objects.all()
        if title:
            qs=qs.filter(title__icontains=title)
        if date:
            try:
                date=datetime.datetime.strptime(date, '%Y-%m-%d').date()
                qs=qs.filter(created_at=date)
            except:
                pass 

        if price_from and price_to:
            qs=qs.filter(
                Q(productvariantprice__price__gte=price_from),
                Q(productvariantprice__price__lte=price_to),
            )
        if variant:
            qs=qs.filter( 
                Q(productvariantprice__product_variant_one__variant_title__icontains=variant)|
                Q(productvariantprice__product_variant_two__variant_title__icontains=variant)|
                Q(productvariantprice__product_variant_three__variant_title__icontains=variant),
                )

        return qs

    def get_context_data(self,**kwargs):
        context = super(ProductList,self).get_context_data(**kwargs)
        # context['variants']=Variant.objects.all()
        variant_grp={}

        for pv in ProductVariant.objects.all().select_related('variant'):
            if pv.variant.title in variant_grp:
                variant_grp[pv.variant.title].add(pv.variant_title.lower())
            else:
                variant_grp[pv.variant.title]=set([pv.variant_title.lower()])

            
        context['variant_grp']=variant_grp
        
    
        return context

src/product/views/variant.py
from django.views import generic
from django.views.generic import ListView, CreateView, UpdateView

from product.forms import VariantForm
from product.models import Variant


class BaseVariantView(generic.View):
    form_class = VariantForm
    model = Variant
    template_name = 'variants/create.html'
    success_url = '/product/variants'


class VariantView(BaseVariantView, ListView):
    template_name = 'variants/list.html'
    paginate_by = 10

    def get_queryset(self):
        filter_string = {}
        print(self.request.GET)
        for key in self.request.GET:
            if self.request.GET.get(key):
                filter_string[key] = self.request.GET.get(key)
        return Variant.objects.filter(**filter_string)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = True
        context['request'] = ''
        if self.request.GET:
            context['request'] = self.request.GET['title__icontains']
        return context


class VariantCreateView(BaseVariantView, CreateView):
    pass


class VariantEditView(BaseVariantView, UpdateView):
    pk_url_kwarg = 'id'

src/product/templates/products/create.html
{% extends 'backend/base.html' %}

{% block title %} Create Product {% endblock %}

{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Create Product</h1>
    <a href="{% url 'product:create.product' %}" class="float-right btn btn-primary">All Product</a>
</div>

<div id="app">
    <create-product :variants="{{variants|safe}}"></create-product>
</div>

{% endblock %}

src/product/templates/products/list.html
{% extends 'backend/base.html' %}
{% load product_tags %}
{% block title %} Product List {% endblock %}

{% block content %}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Products</h1>
</div>


<div class="card">
    <form action="" method="get" class="card-header">
        <div class="form-row justify-content-between">
            <div class="col-md-2">
                <input type="text" name="title" placeholder="Product Title" class="form-control">
            </div>
            <div class="col-md-2">
                <select name="variant" id="" class="form-control">
                    <option selected disabled>--Select A Variant--</option>
                    <!-- {{variant_grp}} -->
                    {%for key,vals in variant_grp.items%}
                    <optgroup label="{{key}}">
                        {%for val in vals%}
                        <option value="{{val}}">{{val}}</option>                        
                        {%endfor%}
                    </optgroup>
                    {%endfor%}

                </select>
            </div>

            <div class="col-md-3">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Price Range</span>
                    </div>
                    <input type="text" name="price_from" aria-label="First name" placeholder="From"
                           class="form-control">
                    <input type="text" name="price_to" aria-label="Last name" placeholder="To" class="form-control">
                </div>
            </div>
            <div class="col-md-2">
                <input type="date" name="date"  placeholder="Date" class="form-control">
            </div>
            <div class="col-md-1">
                <button type="submit" class="btn btn-primary float-right"><i class="fa fa-search"></i></button>
            </div>
        </div>
    </form>

    <div class="card-body">
        <div class="table-response">
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Variant</th>
                    <th width="150px">Action</th>
                </tr>
                </thead>

                <tbody>
                {%for object in object_list%}
                <tr>
                    <td>{{object.id}}</td>
                    <td class="" style="width: 15%;">{{object.title}} <br> Created at : {{object.created_at|timesince}}</td>
                    <td style="width: 30%;">{{object.description}}</td>
                    <td>
                       
                        {%with product_varients_and_price=object.productvariantprice_set.all%}
                        <dl class="row mb-0" style="height: 80px; overflow: hidden" id="variant{{object.id}}">

                            <dt class="col-sm-4 pb-0">
                                {%for obj  in product_varients_and_price%}
                                <div class="mb-2 ">
                                    {{obj}}
                                </div>
                                {%endfor%}
                                
                                
                            </dt>
                            <dd class="col-sm-8">
                                {%for obj  in product_varients_and_price%}
                                <dl class="row mb-2">
                                    <dt class="col-sm-4 pb-0">Price : {{obj.price}}</dt>
                                    <dd class="col-sm-8 pb-0">InStock : {{obj.stock}}</dd>
                                </dl>
                                {%endfor%}
                                

                            </dd>
                        </dl>
                        {%endwith%}
                        <button onclick="$('#variant{{object.id}}').toggleClass('h-auto')" class="btn btn-sm btn-link">Show more
                        </button>
                    </td>
                    <td>
                        <div class="btn-group btn-group-sm">
                            <a href="{%url 'product:update.product' pk=object.id%}" class="btn btn-success">Edit</a>
                        </div>
                    </td>
                </tr>
                {%endfor%}
                </tbody>

            </table>
        </div>

    </div>

    <div class="card-footer">
        <div class="row justify-content-between">
            <div class="col-md-6">
                <p>Showing {{page_obj.start_index}} to {{page_obj.end_index}} out of {{page_obj.paginator.count}}</p>
                
            </div>
            <div class="col-md-4">

 
            
            

              {% if is_paginated %}
              <nav aria-label="Page navigation "></nav>
              <ul class="pagination justify-content-end ">
                  {% if page_obj.has_previous %}
                  <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">&laquo;</a></li>
                  {% else %}
                  <li class="page-item disabled"><span class="page-link" >&laquo;</span></li>
                  {% endif %}

                  {% get_proper_elided_page_range paginator page_obj.number as page_range %}

                  {% for i in page_range %}
                  {% if page_obj.number == i %}
                  <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only"></span> </span></li>
                  {% else %}
                    {% if i == paginator.ELLIPSIS %}
                    <li class="page-item"><a class="page-link" >{{ paginator.ELLIPSIS }}</a></li>
                    {%else%}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>

                    {%endif%}
                  {% endif %}
                  {% endfor %}
                  {% if page_obj.has_next %}
                  <li  class="page-item"><a class="page-link"href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                  {% else %}
                  <li class="page-item disabled"><a class="page-link">&raquo;</a></li>
                  {% endif %}
              </ul>
          </nav>
              {% endif %}



           

            </div>
        </div>
    </div>
</div>
{% endblock %}

src/product/templates/products/update.html
{% extends 'backend/base.html' %}

{% block title %} Updating Product {% endblock %}

{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Update Product</h1>
    <a href="{% url 'product:create.product' %}" class="float-right btn btn-primary">All Product</a>
</div>

<div id="app">
    <update-product :variants="{{variants|safe}}" :pk={{pk}} ></update-product>
</div>

{% endblock %}